name: Continuous Integration

on:
  push:
    branches:
      - main
      - next
      - wip
  pull_request:

jobs:
  ci:
    name: "${{ matrix.m.type }}: ${{ matrix.m.name }}"
    strategy:
      fail-fast: true
      matrix:
        m:
          - type: board
            name: arduino-uno
            examples: true
          - type: mcu
            name: atmega328pb
            spec: atmega328p
            crate: atmega-hal
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly-2022-06-13
          components: rust-src
      - name: Install avr-gcc, binutils, and libc
        run: sudo apt-get install -y avr-libc binutils-avr gcc-avr pkg-config build-essential
      - name: Compile board crate
        if: "${{ matrix.m.type == 'board' && !matrix.m.examples }}"
        run: cd "arduino-hal/" && cargo build --features "${{ matrix.m.name }}"
  arvdude:
    name: "arvdude"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: check
      - name: Install libs
        run: sudo apt-get update && sudo apt-get install -y avrdude libudev-dev
      - name: Check arvdude
        run: |
          cargo check --manifest-path ravedude/Cargo.toml